### ISSUE TITLE
Mostrar sempre as livrarias com os outros preços

### ISSUE THREAD

**Issue by gadelhas** [Lanrutcon/MaisBarato-LivrariasPortuguesas#1]
Devia-se mostrar sempre um ícone ou mesmo a lista de livrarias para podermos sempre ver o preço de outras livrarias.

### Motivo:
Muitas vezes carrega-se um website e esse vai para segundo plano, e depois quando volto à tab o preço de outras livrarias já desapareceu.

**Comment by Lanrutcon** [comment]
Já é possível fazer com que a janela dos preços esteja sempre visível.
Obrigado pela sugestão.
